### PR TITLE
Fixes #964, #965 - Remove validation checks 

### LINKED ISSUE #964: Recursive definitions
I am trying to define a model similar to:
```
entity Exception {
	optional cause as Exception
}
```
Currently, it fails with: Object property type has circular reference

What is the best way to model this?

### PR DESCRIPTION
**Pull request by Ebolon**
Remove validation checks for datatype property recursion and same name validation for function block operation name.

### CODE REVIEW

**Comment by aedelmann** [comment]
I’d be careful removing the recursion check as all generators need to be verified that they handle the recursion. Also the vorto perspective has to handle it. Can u make these changes ?

**Comment by Ebolon** [comment]
Yep, I take care of this. Maybe it is now time for some unit tests for the generators :)

**Comment by aedelmann** [comment]
HI @Ebolon 
Can you check your PR. It says Merge conflicts. I did quite a bit of changes lately, where I put the editors in a different folder structure. Also I removed the Eclipse Toolset, as we will be not supporting the Eclipse plugins any longer. Instead, I added an initial version of a simple web-based editing functionality in the Vorto Repository (using simple javascript ACE editor).

**Comment by Ebolon** [comment]
Closing this for now. I open a new PR when I got the time to take care of this change.

**Pull request closed without merging**
