### PR TITLE
updated document "how to implement a code generator"; Fixes #170; 

### LINKED ISSUE #170: Developer Documentation "How to implement a code generator"
The current documentation about how to implement a generator is out-dated. 
This developer documentation should explain:
1) How to get started quickly with Vorto Generator Wizard in Eclipse
2) Implement a small and easy generator that can be run in Eclipse & server side
3) Extend the generator with using mappings + Mapping API to generate a variation.

### PR DESCRIPTION
**Pull request by gavinying**
Signed-off-by: Ying Shaodong <helloysd@gmail.com>

### CODE REVIEW

**Comment by gavinying** [comment]
@MichaelGuenther Please review this.

**Comment by aedelmann** [comment]
Hi Shaodong, 
looks pretty good. 
I have some points for improvements:
1. Can you also explain in your tutorial how to provide the generator as a micro service ?
2. I think it would also be quite cool, if you could make your hello world generator understand mappings? That would mean, you explain a little how the mapping API is used in the generator. 
3. At the moment, we are offering some utility classes, such as ChainedGeneratorTask or CopyResourcesTask etc. If you could mention those also as part of your hello world generator ?

Thanks!

Cheers, Alex

**Comment by aedelmann** [comment]
Hi @gavinying 
the structure of this chapter looks nice!
Something to improve: the explanation of the code generator and particularly the mappings are not quite clear yet. If you could find another more descriptive (more realistic) example to illustrate it. Mappings are used to map the information meta model to another platform specific model e.g. function block operations to HTTP methods , like PUT, POST. 

Cheers, Alex

**Comment by MichaelGuenther** [comment]
Hi @aedelmann, I didn't mention you in my pull request because I don't know if somebody should still work on this branch (see your last comment). Regarding the current content, my review is complete.
Regards
Michael

**Pull request merged**
