### PR TITLE
Ux/2288 add a search functionality for repository sysadmins in namespace management

### PR DESCRIPTION
**Pull request by mena-bosch**
### Please don't merge yet

This branch incorporates the latest changes from #2287 and should only be merged once the latter has been retested and merged. 

The changes compared to #2287 are minimal (only some UI improvement for sysadmins).

### CODE REVIEW

**Comment by mena-bosch** [comment]
Generator lambda build on travis is failing, despite this change set not impacting on generator. 
Could it be anything related to #2294 @kolotu ?

**Comment by mena-bosch** [comment]
> Generator lambda build on travis is failing, despite this change set not impacting on generator.
> Could it be anything related to #2294 @kolotu ?

Looks like @t-gauss managed to replicate something similar while building the dev branch locally, but I cannot myself. Might be related to the license plugin instead...

**Comment by kolotu** [comment]
@kolotu @t-gauss yes the license header on NamespaceController.java is not correct that's why it is failing as it should. From looking at the diff the line breaks have changed.

**Comment by mena-bosch** [comment]
> @kolotu @t-gauss yes the license header on NamespaceController.java is not correct that's why it is failing as it should. From looking at the diff the line breaks have changed.

Thanks, wasn't immediately clear from the travis logs. Trying with line breaking at different offset now.

**Pull request merged**
