### PR TITLE
[1250] Fix error handling in Generators Health check

### PR DESCRIPTION
**Pull request by georgschmidtdumont**
By default the Error Handler for the Spring Rest-Template throws an
exception when the status code in a response is not 2xx.
Hence the check whether a Generator is available is changed from
checking the status code to handling the exception thrown by the
Rest-Templates error handler.

Signed-off-by: Schmidt-Dumont Georg (BCI/ESW24) <georg.schmidt-dumont@de.bosch.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=1250

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=1250

**Comment by aedelmann** [comment]
Hi @georgschmidtdumont 
I see that you do not have any integration tests written for the health. Would you add that ? 
I guess it could test the following:
1) Repository without any generators, to check if the repository is up
2) Repository with registered generator,  to check that repository is up but generator is not reachable

What do you think ?

**Comment by georgschmidtdumont** [comment]
Hi @aedelmann,

that is what the tests in the GeneratorsHealthCheckTest class cover. I don't see any advantage in creating any additional tests.

**Pull request merged**
