### PR TITLE
Feature/2046 1833 improved repository search

### PR DESCRIPTION
**Pull request by mena-bosch**
Large search improvement/documentation/test/refactory.

Contents in at bird sight:

1. Separation of input parsing logic vs dedicated logic for each search service
2. Simple search service logic completely re-written
3. 135 search tests (most of which new) in repository-core. Including mixed integration and pure unit tests (the latter on the common parsing mechanism)
4. Documentation and plenty of javadoc
5. REST endpoint for sys admins to force re-create the index (rather than just reindex the model) - in addition to previous endpoint and with additional entry in UI form
6. Search is much leninent to user input, supports multiple tags and wildcards, etc. see docs

Not included: 
a. Integration tests for Elasticsearch - those are in the works, but will be added in a different branch

### CODE REVIEW

**Comment by aedelmann** [comment]
@mena-bosch 
1) You build fails due to a broken link to Vorto Web Site. U might wanna try https://www.eclipse.org/vorto

**Comment by mena-bosch** [comment]
> @mena-bosch
> 
>     1. You build fails due to a broken link to Vorto Web Site. U might wanna try https://www.eclipse.org/vorto

Hey @aedelmann , thanks for your help! 
In hindsight I think this is not related to the protocol and more to the fact that, unbeknownst to me, my IDE decided it would be useful to wrap the copy-pasted link to Vorto home in double parentheses...
Trying again with both https and parenthesis fixed momentarily.

**Comment by aedelmann** [comment]
Hi @mena-bosch 
I created another issue for the Released REST Endpoint Bug: https://github.com/eclipse/vorto/issues/2137

**Comment by mena-bosch** [comment]
Sigh. 
Looks like latest merge of #2135 today made my test class' usage of org.eclipse.vorto.repository.domain.User unsupported. 
Merging again from dev, fixing problematic invocations and pushing again shortly.

**Pull request merged**
