### PR TITLE
Add clustering capabilities

### PR DESCRIPTION
**Pull request by Scriptkiddi**
This pull request will also upgrade the Modeshape version to 5.4.1.Final
and besides that it also refactors the settings yml files because there
was quite a lot of overlap between those

Signed-off-by: Fritz Otlinghaus <fritz@otlinghaus.it>

### CODE REVIEW

**Comment by Scriptkiddi** [comment]
CQ for 
modeshape 5.4.1
and
org.springframework.session:spring-session-jdbc

**Comment by Scriptkiddi** [comment]
Is this still needed or can it be closed?

**Comment by aedelmann** [comment]
We need it  Can u fix the conflicts ?

**Comment by Scriptkiddi** [comment]
will do

**Pull request closed without merging**
