### PR TITLE
Closes #258, Closes #249

### LINKED ISSUE #249: System Requirements for using Vorto Toolset

### LINKED ISSUE #258: Installation Guide Vorto Toolset
Automatic Installation:
IDE for Manufacturers : https://marketplace.yatta.de/profiles/ziXJ
IDE for Platform Vendors: https://marketplace.yatta.de/profiles/4PTx
IDE for Solution Developers: https://marketplace.yatta.de/profiles/KezX

Manual Installation:

1) Prerequisite:
- Mars for DSL Developers
- Java 8

Getting toolset:
1) Update Site 
2) Update Archive
3) Eclipse Marketplace

### PR DESCRIPTION
**Pull request by MichaelGuenther**
Closes #258
Closes #249

Signed-off-by: Guenther Michael (INST/BSV2-TD) <Michael.Guenther@bosch-si.com>

### CODE REVIEW

**Comment by aedelmann** [comment]
Hi michael, could you please resolve this merge conflicts and Pull Request again?
Thanks. 

Cheers, Alex

**Comment by MichaelGuenther** [comment]
Alex, how can I do that? Shall I just use my working branch again?

**Comment by aedelmann** [comment]
Yes, you would need to rebase your branch with development. They have deviated ever since you branched off from dev:
`git pull development`
`git checkout mybranch `
`git rebase development` There will then be merge conflicts, please correct them using a merge editor. 
`git push mybranch` Then Pull Request again.

**Comment by aedelmann** [comment]
Hi Michael, 
I think something went wrong when you merged because I don't think you have changed 282 files.
Could you please correct that?

Cheers, Alex

**Comment by MichaelGuenther** [comment]
Alex,
now I'm completely confused - in my local working branch as well as in local development branch many folders are gone! How can I get them back?
Michael

**Pull request merged**
