### PR TITLE
Open shared model in editor when clicked in repo browser

### LINKED ISSUE #91: Preview of a shared model found by the toolset - repository browser.
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=471510

### PR DESCRIPTION
**Pull request by erlemantos**
Open a shared model in the editor when it is clicked from the model repository browser. Closes #91

Signed-off-by: Erle Czar Mantos <erleczar.mantos@bosch-si.com>

### CODE REVIEW

**Comment by aedelmann** [comment]
Hi Erle, 
when the user clicks on the shared model, it will open in the editor window, right? Is this editor window readonly? Because the user should not have an option to edit the previewed file.

**Comment by erlemantos** [comment]
Added some code to make opening the shared model Read-only.

**Comment by aedelmann** [comment]
I have two minor points:
1) Can you rename the temporary files to <modelname>-preview.<extension>
2) Change the option to preview for models by right-click on the model in the table and choose "Preview" menu item

**Comment by erlemantos** [comment]
Now the previewing of the model is done via the context menu (Right click then Preview Model) rather that when you click the model in the repo table.

**Pull request merged**
