### PR TITLE
Fixes #253 - Update DSL Grammar.

### LINKED ISSUE #253: Update DSL Grammar
Additional grammar elements:

- Constraints defintion for operation params & return type
- Documentation of operation params
- Measurement Unit
- new breakable keyword for operation to indicate errors
- Dictionary object type

### PR DESCRIPTION
**Pull request by erlemantos**
@MichaelGuenther Here's the branch for this documentation task.

Signed-off-by: Erle Czar Mantos <erleczar.mantos@bosch-si.com>

### CODE REVIEW

**Comment by aedelmann** [comment]
Hi @erlemantos 
could you please merge these DSL changes with the existing grammar documentation?

**Comment by aedelmann** [comment]
@MichaelGuenther  @erlemantos What is the status of this Pull Request? It seems to be a single MD file but does not yet fit into our current documentation.

**Comment by erlemantos** [comment]
I've already updated the .md files for the DSL appendix. As to the tutorial that I wrote for the DSL updates, I don't know where to put that.

**Comment by aedelmann** [comment]
@erlemantos  @MichaelGuenther 
The improvement markdown has to be somewhat merged with the appendix of function block and datatype where each element is described in the table. At the moment the improvement MD is not referenced from anywhere, how can a user find it ?

**Comment by MichaelGuenther** [comment]
@erlemantos, @aedelmann,
I recognize two task:

- Updating the examples in the Model DSL Reference  
  Please provide reasonable examples updated according to the DSL improvements.
- Updating the syntaxin the Model DSL Reference   
  Please provide information (sources) I can incorporate.

Regards
Michael

**Comment by aedelmann** [comment]
@erlemantos 
What is the status of adding in the proposals given by Michael?

**Comment by erlemantos** [comment]
Hi @aedelmann , @MichaelGuenther 

I just added some commits to fix the two points pointed out on Michael's comment:

 1) Moved entity and enum to datatype appendix, as they should be in datatype.
 2) Examples in the function block appendix that shows the improvements to the DSL
 3) An entire new section of datatype appendix (Semantics) that expounds more on the
 datatype.
 4) Modified the function block and datatype syntax to reflect improvements
 to the DSL

**Pull request merged**
