### PR TITLE
ThingWorx Example Code Generato

### PR DESCRIPTION
**Pull request by StephenHarmon**
Author: Stephen Harmon <stephen.harmon@thingworx.com>
Date: Mon Jan 18 17:00:00 2016
CLA: Valid CLA on file

[485502] - ThingWorx Example Code Generator

The ThingWorx Vorto Code Generator generates ThingWorx specific code that links Vorto Models to ThingWorx Things.
This pull request contains the functionality that has been presented at the LiveWorx Stuttgart last year.

The current version represents a minimum viable demo of the code generator. Enhancements being worked on now include:

* The current version supports the mapping of simple data types like int, String, and double. Vorto provides rich functionality for modeling custom data types. The next version will contain added support for custom data types.
* This version uses the jackson-core-2.6.0 JSON library. It is imported as a jar in a lib directory. The preferred OSGI pattern is for libraries to be embedded in a bundle. The next version will package the library as a bundle.

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=485502
Signed-off-by: Stephen Harmon <stephen.harmon@thingworx.com>

### CODE REVIEW

**Comment by StephenHarmon** [comment]
It looks like I did not sign my commit properly. How should I fix the issue without making things more complicated than they have to be?

**Comment by aedelmann** [comment]
Hi Steve, 
your Pull Request looking nice :)
Seems like that your sign-off did not quite work. Did you sign a CLA with Eclipse? Also make sure that your add your Github user Id to your Eclipse User Profile settings. 
Also please try to squash your commits into one commit in order to sign-off only the single commit.

**Comment by kartben** [comment]
Steve,

The Signed-off-by header should be inserted at the commit level, not in the description of the PR.
What's more, you should rely on eg the "-s" Git command line parameter to create the Signed-off-by header so as it has the proper format (it looks like the Signed-off-by header in your PR comment does not put the email address between < > signs, for example)...

Your best move would be to amend the commits in your StephenHarmon:thingworx-code-generator branch so as they include the Signed-off-by header, and push-force that branch. See e.g http://stackoverflow.com/a/13043757

HTH

**Comment by kartben** [comment]
@aedelmann please make sure to file a CQ for the Jackson dependency

**Comment by aedelmann** [comment]
@StephenHarmon  
Would it be possible to use jackson-core 2.6.2 instead. This lib is already CQ approved and would speed up the Pull Request approval.

**Comment by aedelmann** [comment]
Hi Steve, 
could you please squash your commits into a single commit (commit -squash) and sign it off.  That way the Pull Request should pass IP Validation. 
Thank you! 
Cheers, Alex

**Comment by StephenHarmon** [comment]
Alex,

I'm starting fresh, with a new pull request. You'll see it soon.

Thanks,
Steve

**Pull request closed without merging**
