### PR TITLE
Fixes #407

### LINKED ISSUE #407: Web Editor for entities and enums

### PR DESCRIPTION
**Pull request by shiv12095**
Signed-off-by: shiv12095 shiv12095@iiitd.ac.in

### CODE REVIEW

**Comment by aedelmann** [comment]
Hi Shiv, there seems to be a problem with the IP validation. Did you sign-off your commit properly?

**Comment by shiv12095** [comment]
I guess not, I will create another pull request then

**Comment by aedelmann** [comment]
Hi Shiv, 
thanks for the IP fix. 
I noticed that your new ide bundles are not referenced in the editor feature(s). that is taken during installation of the vorto plugins. Could you add that please also?

Thanks!

**Comment by shiv12095** [comment]
Hi Alex,

According to the logs,  the pom.xml of devtool cannot find the package datatype.web
I added this package as a part of this pull request.

This issue seems to be similar to the one we encountered in one of our previous builds https://travis-ci.org/eclipse/vorto/builds/163130725

Last time we had this, we first built the bundles

Can you fix the Travis build to first build the bundles and then server/pom.xml. That might resolve the issue

**Pull request merged**
