### PR TITLE
Importing Eclipse Ditto namespaced (example) models

### PR DESCRIPTION
**Pull request by thjaeckle**
from Eclipse Vorto repository export

Blocked by approval of CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23212

### CODE REVIEW

**Comment by thjaeckle** [comment]
@t-gauss please advise on how to get the PR checks green

**Comment by kolotu** [comment]
@thjaeckle you cannot get the checks green, as the CI pipelines are no longer functional. The only relevant check is the ECA and that one is green.

**Comment by t-gauss** [comment]
Hi @thjaeckle. Pipeline is broken. We will look into it and get back to you.

**Comment by t-gauss** [comment]
@thjaeckle as @kolotu mentioned we can merge as soon as the CQ is approved.

**Comment by thjaeckle** [comment]
@t-gauss what's open here to get the PR merged?

**Comment by t-gauss** [comment]
@thjaeckle - sorry for the delay. I will do it today.

**Pull request merged**
