### PR TITLE
Changed the menu from "Check-in to repository" to "Share"

### PR DESCRIPTION
**Pull request by erlemantos**

### CODE REVIEW

**Comment by aedelmann** [comment]
Did you get in touch with Eclipse to see what the problem might be in regards to the ip-validation?

**Comment by erlemantos** [comment]
I already filed a bug with screenshots at Eclipse community under Github.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=476934

**Comment by erlemantos** [comment]
Apparently, the ip-validation problem is a known error. They marked my bug as Duplicate.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=468552

**Comment by erlemantos** [comment]
Closing pull request due to a bug in Eclipse causing ip-validation to fail.

**Pull request closed without merging**
