### PR TITLE
Migrated all com.bosch.iot.suite.edge.services.da namespaced Vorto models

### PR DESCRIPTION
**Pull request by lubomir-mitev**
Migrated all com.bosch.iot.suite.edge.services.da namespaced Vorto models

Signed-off-by: Lubomir Mitev <lubomir.mitev@bosch.io>

### CODE REVIEW

**Comment by kolotu** [comment]
Hi @lubomir-mitev you need to sign the Eclipse ECA https://www.eclipse.org/legal/ECA.php. Once that is done, we can re-trigger the check.

**Comment by lubomir-mitev** [comment]
Hi @kolotu something is wrong. Old email is used for verification (l.mitev@prosyst.bg). Actually the github account is configured with lubomir.mitev@bosch.io. How do you get the old email? Eclipse ECA also is signed with the new email lubomir.mitev@bosch.io

**Comment by lubomir-mitev** [comment]
I found the mistake - its my mistake. May be new PR is better to create with correct information because it's not possible to change the Author

**Comment by kolotu** [comment]
@lubomir-mitev sure you can create a new PR and close this one.

**Pull request closed without merging**
