### PR TITLE
bugfix/2137 List of Vorto Function Blocks in Info Model Creation wiza…

### PR DESCRIPTION
**Pull request by mena-bosch**
…rd shows all released Functionblocks

1. Removed "/releases" API endpoint and replaced in angular with hardcoded search
2. As function does not require a parameter anymore, de-parametrized in angular and html template

Signed-off-by: Menahem Julien Raccah Lisei <menahemjulien.raccahlisei@bosch-si.com>

### CODE REVIEW

**Comment by mena-bosch** [comment]
Hi @aedelmann , something for you tomorrow... I have a compliance check failure on this one, but I cannot see the root cause due to "insufficient permissions".

**Comment by aedelmann** [comment]
Hi @mena-bosch 
this is not caused by your PR but with some update in the CLM Database. You have been the lucky one where the new DB content kicked in :) I already fixed it in the CLM db and your PR was successful. Cheers

**Comment by mena-bosch** [comment]
@aedelmann ah thanks. Feeling I'm always lucky like that :grin: Just to make sure, is the DB update the reason why my access was denied with insufficient permissions?

**Comment by aedelmann** [comment]
@mena-bosch No, this might be related, that your user is not associated to the Vorto application ID. I can try to add you there.

**Comment by mena-bosch** [comment]
@aedelmann oki thanks, let me know!

**Pull request merged**
